# Generated by Django 6.0.3 on 2026-04-20 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_user'),
        ('users', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_order_user', to='users.user'),
        ),
    ]
